// src/app/components/layout.tsx
import { Inter } from "next/font/google";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        {/* You can include page metadata and links to fonts here */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* Other head elements like favicons, stylesheets, etc. */}
      </Head>
      <body className={inter.className}>
        {children}
      </body>
    </>
  );
};

export default RootLayout;
