import { Inter } from "next/font/google";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* Include other head elements like favicons, stylesheets, etc. */}
        {/* Example:
        <link rel="stylesheet" href="/path/to/styles.css" />
        */}
      </Head>
      <div className={inter.className}>
        {children}
      </div>
    </>
  );
};

export default RootLayout;
